name: Build & Test (.NET)
# Runs build and tests for all pushes and pull requests on main

on:
  push:
    branches: [ "main" ]           # Trigger on pushes to main branch
  pull_request:
    branches: [ "main" ]           # Trigger on PRs targeting main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest         # Use latest Ubuntu runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Checkout repository

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Install .NET 8 SDK

      - name: Restore dependencies
        run: dotnet restore        # Restore NuGet packages
        working-directory: ./src   # Run inside the src folder

      - name: Build project
        run: dotnet build --no-restore --configuration Release
        working-directory: ./src   # Build in Release mode, skip restore

      - name: Run tests with coverage
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage" --results-directory ./TestResults
        working-directory: ./src   # Run unit tests and collect coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./src/TestResults/**/coverage.cobertura.xml  # Coverage report path
          token: ${{ secrets.CODECOV_TOKEN }}                 # Auth token from repo secrets
          fail_ci_if_error: true                              # Fail if Codecov upload fails
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}