name: Update Homebrew Formula

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository homebrew-tap
        uses: actions/checkout@v4
        with:
          repository: S9yN37/homebrew-tap
          token: ${{ secrets.TAP_TOKEN }}
          ref: main

      - name: Get release info
        id: release
        uses: actions/github-script@v6
        with:
          script: |
            let release;
            if (context.payload.release) {
              // Triggered by "release"
              release = context.payload.release;
            } else {
              // Triggered by "workflow_dispatch"
              const latest = await github.rest.repos.getLatestRelease({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              release = latest.data;
            }

            core.setOutput("tag", release.tag_name);
            core.setOutput("url_x64", release.assets.find(a => a.name.includes("osx-x64")).browser_download_url);
            core.setOutput("url_arm", release.assets.find(a => a.name.includes("osx-arm64")).browser_download_url);

      - name: Download & compute sha256 (x64)
        run: |
          curl -L ${{ steps.release.outputs.url_x64 }} -o x64.tar.gz
          echo "sha256_x64=$(shasum -a 256 x64.tar.gz | cut -d ' ' -f1)" >> $GITHUB_ENV

      - name: Download & compute sha256 (arm64)
        run: |
          curl -L ${{ steps.release.outputs.url_arm }} -o arm64.tar.gz
          echo "sha256_arm=$(shasum -a 256 arm64.tar.gz | cut -d ' ' -f1)" >> $GITHUB_ENV

      - name: Update Formula
        run: |
          sed -i "s/version \".*\"/version \"${{ steps.release.outputs.tag }}\"/" Formula/subtitletools.rb
          sed -i "s#osx-x64.tar.gz\".*#osx-x64.tar.gz\"\n      sha256 \"${sha256_x64}\"#" Formula/subtitletools.rb
          sed -i "s#osx-arm64.tar.gz\".*#osx-arm64.tar.gz\"\n      sha256 \"${sha256_arm}\"#" Formula/subtitletools.rb

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/subtitletools.rb
          git commit -m "Update SubtitleTools to ${{ steps.release.outputs.tag }}" || echo "No changes to commit"
          git push